#!/usr/bin/env python

import rospy
from std_msgs.msg import Int32MultiArray

def talker():
    pub = rospy.Publisher('chatter', Int32MultiArray, queue_size=10)
    rospy.init_node('talker', anonymous=True)
    rate = rospy.Rate(1) # 10hz
    while not rospy.is_shutdown():
		a = [1,2,3]
		array = Int32MultiArray(data = a)
		rospy.loginfo(array)
		pub.publish(array)
		rate.sleep()

if __name__ == '__main__':
    try:
        talker()
    except rospy.ROSInterruptException:
        pass
